# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Hostpital_Management_reports',
    'version': '1.0',
    'category': 'Extra Tools',
    'License' :'AGPL -3',
    'sequence': 5,
    'summary': 'Module of Reports',
    'description': "",
    'website': 'https://www.odoo.com/page/crm',
    'depends': ['mail','sale','account','board'],
    'data': ['wizards/create_appointment.xml',
             'views/patient.xml',
             'views/sale_order.xml',
             'security/ir.model.access.csv',
             'data/sequence.xml',
             'data\data.xml',
             'data\cron.xml',
             'views/appointment.xml',
             'views/template.xml',
             'views/settings.xml',
             'views/website_form.xml',
             'reports/report.xml',
             'reports/appointment.xml',
             'reports/sale_report_inherit.xml',
             'reports/patient_card.xml',
             'views/doctor.xml',
             'views/dashboard.xml',
             'data/mail_template.xml',
             'security/security.xml',
             ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}